export type Profile = {
  id: string
  full_name: string
  email: string
  phone: string | null
  avatar_url: string | null
  is_active: boolean
  created_at: string
  updated_at: string
}

export type RoleCode =
  | 'ADMIN'
  | 'DIRECAO'
  | 'GERENTE_COMERCIAL'
  | 'VENDEDOR'
  | 'FINANCEIRO'
  | 'PEDAGOGICO'
  | 'PROFESSOR'
  | 'RECEPCAO'

export type PermissionCode =
  | 'dashboard.view'
  | 'crm.view'
  | 'crm.view_all'
  | 'crm.create'
  | 'crm.edit'
  | 'crm.assign'
  | 'crm.move_stage'
  | 'crm.close_lost'
  | 'crm.activities.manage'
  | 'crm.activities.manage_all'
  | 'crm.manage_catalog'
  | 'crm.reports'
  | 'courses.view'
  | 'courses.manage'
  | 'sales.view'
  | 'sales.create'
  | 'sales.approve'
  | 'finance.view'
  | 'finance.create'
  | 'finance.receive'
  | 'finance.export'
  | 'academic.view'
  | 'academic.manage'
  | 'attendance.create'
  | 'commissions.view'
  | 'commissions.approve'
  | 'users.view'
  | 'users.manage'
  | 'reports.view'
  | 'reports.export'
  | 'audit.view'
  | 'settings.view'
  | 'settings.manage'
  | 'people.view'
  | 'people.create'
  | 'people.edit'
  | 'students.view'
  | 'students.create'
  | 'students.edit'
  | 'students.manage_status'
  | 'students.view_sensitive'
  | 'guardians.view'
  | 'guardians.manage'

export type AuditAction =
  | 'auth.login'
  | 'auth.logout'
  | 'profile.update'
  | 'administration.update'
  | 'student.created'
  | 'student.updated'
  | 'student.status_changed'
  | 'guardian.linked'
  | 'guardian.updated'
  | 'guardian.unlinked'
  | 'crm.lead_created'
  | 'crm.lead_updated'
  | 'crm.lead_assigned'
  | 'crm.stage_changed'
  | 'crm.activity_created'
  | 'crm.activity_completed'
  | 'crm.activity_rescheduled'
  | 'crm.lead_lost'
  | 'crm.course_created'
  | 'crm.course_updated'
