import type { ReactNode } from 'react'
import { cn } from '@/lib/utils'
import { Card, Select } from './core'
export function Table({ children, className }: { children: ReactNode; className?: string }) { return <div className="overflow-x-auto"><table className={cn('w-full border-collapse text-left text-sm', className)}>{children}</table></div> }

type DataColumn<T> = { key: string; header: string; cell: (row: T) => ReactNode; priority?: 'high' | 'medium' | 'low'; hideOn?: string }
export function DataTable<T>({ data, columns, getKey }: { data: T[]; columns: DataColumn<T>[]; getKey: (row: T) => string }) {
  return <Table><thead><tr className="border-b bg-navy-50/60">{columns.map((column) => <th key={column.key} className={cn('px-4 py-3 text-xs font-semibold uppercase tracking-wider text-muted', column.priority === 'low' && 'hidden md:table-cell', column.priority === 'medium' && 'hidden sm:table-cell')}>{column.header}</th>)}</tr></thead><tbody className="divide-y">{data.map((row) => <tr key={getKey(row)} className="hover:bg-slate-50">{columns.map((column) => <td key={column.key} className={cn('px-4 py-4', column.priority === 'low' && 'hidden md:table-cell', column.priority === 'medium' && 'hidden sm:table-cell')}>{column.cell(row)}</td>)}</tr>)}</tbody></Table>
}
export function MultiSelect({ options, value, onChange, label = 'Selecionar' }: { options: string[]; value: string[]; onChange: (value: string[]) => void; label?: string }) { return <fieldset className="rounded-lg border p-3"><legend className="px-1 text-xs font-semibold">{label}</legend>{options.map((option) => <label key={option} className="flex min-h-9 items-center gap-2 text-sm"><input type="checkbox" checked={value.includes(option)} onChange={() => onChange(value.includes(option) ? value.filter((x) => x !== option) : [...value, option])} />{option}</label>)}</fieldset> }
export function DatePicker(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input type="date" className="min-h-11 rounded-lg border bg-white px-3 text-sm" {...props} /> }
export function DateRangePicker({ start, end, onChange }: { start: string; end: string; onChange: (value: { start: string; end: string }) => void }) { return <div className="flex flex-wrap gap-2"><DatePicker aria-label="Data inicial" value={start} onChange={(event) => onChange({ start: event.target.value, end })} /><DatePicker aria-label="Data final" value={end} onChange={(event) => onChange({ start, end: event.target.value })} /></div> }
export function Stepper({ steps, current }: { steps: string[]; current: number }) { return <ol className="flex items-center">{steps.map((step, index) => <li key={step} className="flex flex-1 items-center text-xs"><span className={cn('grid size-7 shrink-0 place-items-center rounded-full bg-slate-200 font-semibold', index <= current && 'bg-navy text-white')}>{index + 1}</span><span className="ml-2 hidden sm:block">{step}</span>{index < steps.length - 1 && <span className="mx-2 h-px flex-1 bg-line" />}</li>)}</ol> }
export function Timeline({ items }: { items: { title: string; detail: string }[] }) { return <ol className="space-y-4 border-l border-line pl-5">{items.map((item) => <li key={`${item.title}-${item.detail}`} className="relative"><span className="absolute -left-[25px] top-1 size-2 rounded-full bg-gold" /><p className="text-sm font-semibold">{item.title}</p><p className="text-xs text-muted">{item.detail}</p></li>)}</ol> }
export function KPICard({ label, value, icon: Icon, trend, danger }: { label: string; value: string; icon: React.ElementType; trend?: string; danger?: boolean }) { return <Card className={cn('group flex flex-col justify-between gap-4 p-5 transition duration-fast hover:-translate-y-0.5 hover:shadow-md', danger && 'border-red-200')}><div className="flex items-start justify-between gap-2"><span className={cn('text-sm font-medium text-muted', danger && 'text-red-700')}>{label}</span><Icon className={cn('size-5 text-gold-dark', danger && 'text-red-600')} /></div><div><p className={cn('font-display text-kpi font-semibold leading-9 truncate', danger && 'text-red-700')}>{value}</p>{trend && <p className={cn('mt-2 text-xs font-semibold text-success', danger && 'text-muted')}>{trend}</p>}</div></Card> }
export function CommandPaletteShell({ children }: { children: ReactNode }) { return <div className="overflow-hidden rounded-xl border bg-white">{children}</div> }
export function NativeSelect({ options, ...props }: { options: string[] } & React.SelectHTMLAttributes<HTMLSelectElement>) { return <Select {...props}>{options.map((option) => <option key={option}>{option}</option>)}</Select> }
